name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: pages-${{ github.sha }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # This deploys your whole repo — you can change this if needed

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

  concurrency:
    group: ${{ github.workflow }}-${{ github.sha }}
    cancel-in-progress: true
